### ISSUE TITLE
Duplicated old docs under meltano main site

### ISSUE THREAD

**Issue by elsatch** [meltano/website#16]
As I was testing features, I just stumbled upon an error on Python version. 
Searching for “meltano python version” on Google lead me to https://meltano.com/documentation/getting-started/ 

This documentation suggests using venv instead of the newer pipx version, so I think it's an old version. 

I assume meltano.com/documentation has moved to docs.meltano.com, but the old information is still being displayed in the main site.

**Comment by tayloramurphy** [comment]
this now redirects to https://docs.meltano.com/getting-started/part1
